# Windows

#COPT=/Zi /nologo /W3 /WX- /O2 /Oi /Oy- /GL /D "WIN32" /D "_WINDOWS" /D "NDEBUG" /D "_UNICODE" /D "UNICODE" /Gm- /EHsc /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Gd /analyze-
COPT=/Zi /nologo /W3 /WX- /MT /O2 /Oi /Oy- /DTEST /D "WIN32" /D "_WINDOWS" /D "NDEBUG" /D "_UNICODE" /D "UNICODE" /D "_CRT_SECURE_NO_WARNINGS" /Gm- /EHsc /fp:precise /Zc:wchar_t 


OBJS = test_exec.obj db.obj sqlite3.obj alpdb.obj testmain.obj stdafx.obj

# test_exec.cpp
{..\..\app\win_mfc\fjr_mfc\alps_mfc}.cpp.obj :
	cl $(COPT) /I. /I..\..\app\win_mfc\fjr_mfc\lib\db /I..\..\app\win_mfc\fjr_mfc\lib\alps /c $<

# alpdb.cpp
{..\..\app\win_mfc\fjr_mfc\lib\alps}.cpp.obj :
	cl $(COPT) /I. /I..\..\app\win_mfc\fjr_mfc\lib\db /I..\..\app\win_mfc\fjr_mfc\lib\alps /c $<

# db.cpp
{..\..\app\win_mfc\fjr_mfc\lib\db}.cpp.obj :
	cl $(COPT) /I. /I..\..\app\win_mfc\fjr_mfc\lib\db /I..\..\app\win_mfc\fjr_mfc\lib\alps /c $<

# sqlite3.cpp
{..\..\app\win_mfc\fjr_mfc\lib\db}.c.obj :
	cl $(COPT) /I. /I..\..\app\win_mfc\fjr_mfc\lib\db /c $<

# testmain.cpp
.cpp.obj :
	cl $(COPT) /I. /I..\..\app\win_mfc\fjr_mfc\lib\db /I..\..\app\win_mfc\fjr_mfc\lib\alps /c $<


all : test.exe


test.exe : $(OBJS)
	 link /OUT:$@ $** /INCREMENTAL:NO "imm32.lib"  
clean:
	del *.obj test.exe

#/MANIFEST /ManifestFile:"Release\farert.exe.intermediate.manifest" 
#/ALLOWISOLATION /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /DEBUG /PDB:"C:\home\devel\fjr\app\win_mfc\fjr_mfc\Release\farert.pdb"
#/PGD:"C:\home\devel\fjr\app\win_mfc\fjr_mfc\Release\farert.pgd"
#/SUBSYSTEM:WINDOWS /OPT:REF /OPT:ICF  /LTCG /TLBID:1 /DYNAMICBASE /NXCOMPAT /MACHINE:X86 /ERRORREPORT:QUEUE 


