python rule70.py 中央東線 常磐線
python rule70.py 中央東線 東北線
python rule70.py 中央東線 東北線(埼京線)
python rule70.py 中央東線 東北新幹線
python rule70.py 中央東線 上越新幹線
python rule70.py 中央東線 総武線
python rule70.py 中央東線 京葉線

python rule70.py 常磐線 中央東線 
python rule70.py 東北線 中央東線 
python rule70.py 東北線(埼京線) 中央東線 
python rule70.py 東北新幹線 中央東線 
python rule70.py 上越新幹線 中央東線 
python rule70.py 総武線 中央東線 
python rule70.py 京葉線 中央東線 

python rule70.py 常磐線 常磐線
python rule70.py 常磐線 東北線
python rule70.py 常磐線 東北線(埼京線)
python rule70.py 常磐線 東北新幹線
python rule70.py 常磐線 上越新幹線
python rule70.py 常磐線 総武線
python rule70.py 常磐線 京葉線
python rule70.py 東北線 中央東線 
python rule70.py 東北線 常磐線
python rule70.py 東北線 東北線
python rule70.py 東北線 東北線(埼京線)
python rule70.py 東北線 東北新幹線
python rule70.py 東北線 上越新幹線
python rule70.py 東北線 総武線
python rule70.py 東北線 京葉線
python rule70.py 東北線(埼京線) 中央東線 
python rule70.py 東北線(埼京線) 常磐線
python rule70.py 東北線(埼京線) 東北線
python rule70.py 東北線(埼京線) 東北線(埼京線)
python rule70.py 東北線(埼京線) 東北新幹線
python rule70.py 東北線(埼京線) 上越新幹線
python rule70.py 東北線(埼京線) 総武線
python rule70.py 東北線(埼京線) 京葉線
python rule70.py 東北新幹線 中央東線 
python rule70.py 東北新幹線 常磐線
python rule70.py 東北新幹線 東北線
python rule70.py 東北新幹線 東北線(埼京線)
python rule70.py 東北新幹線 東北新幹線
python rule70.py 東北新幹線 上越新幹線
python rule70.py 東北新幹線 総武線
python rule70.py 東北新幹線 京葉線
python rule70.py 上越新幹線 中央東線 
python rule70.py 上越新幹線 常磐線
python rule70.py 上越新幹線 東北線
python rule70.py 上越新幹線 東北線(埼京線)
python rule70.py 上越新幹線 東北新幹線
python rule70.py 上越新幹線 上越新幹線
python rule70.py 上越新幹線 総武線
python rule70.py 上越新幹線 京葉線
python rule70.py 総武線 中央東線 
python rule70.py 総武線 常磐線
python rule70.py 総武線 東北線
python rule70.py 総武線 東北線(埼京線)
python rule70.py 総武線 東北新幹線
python rule70.py 総武線 上越新幹線
python rule70.py 総武線 総武線
python rule70.py 総武線 京葉線
python rule70.py 京葉線 中央東線 
python rule70.py 京葉線 常磐線
python rule70.py 京葉線 東北線
python rule70.py 京葉線 東北線(埼京線)
python rule70.py 京葉線 東北新幹線
python rule70.py 京葉線 上越新幹線
python rule70.py 京葉線 総武線
python rule70.py 京葉線 京葉線
