# Windows

#COPT=/Zi /nologo /W3 /WX- /O2 /Oi /Oy- /GL /D "WIN32" /D "_WINDOWS" /D "NDEBUG" /D "_UNICODE" /D "UNICODE" /Gm- /EHsc /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Gd /analyze-
COPT=/Zi /nologo /W3 /WX- /MT /O2 /Oi /Oy- /DTEST /D "WIN32" /D "_WINDOWS" /D "NDEBUG" /D "_UNICODE" /D "UNICODE" /Gm- /EHsc /fp:precise /Zc:wchar_t 


OBJS = db.obj sqlite3.obj alpdb.obj testmain.obj stdafx.obj



.cpp.obj :
	cl $(COPT) /I. /c $<


all : test.exe


test.exe : $(OBJS)
	 link /OUT:$@ $** /INCREMENTAL:NO "imm32.lib"  
clean:
	del *.obj test.exe



